on: [push]

name: Build latest

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        page: [flytirol, bikeandfly, hydrogen, gh2di]
    runs-on: ubuntu-latest
    name: Build ${{ matrix.page }} latest
    env:
      NUXT_PAGE: ${{ matrix.page }}
      NUXT_BACKEND: ${{ matrix.page }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '22'
      - run: yarn install
      - run: yarn upgrade --latest
      - name: create .nuxt tsconfig
        run: mkdir .nuxt && echo "{}" > .nuxt/tsconfig.json
      - name: create-public
        run: yarn create-public
      - name: generateMediaInformation
        run: yarn generateMediaInformation
      - name: generateContent
        run: yarn generateContent
      - name: build
        run: yarn build
