on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

name: Build fly-tirol.com

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build fly-tirol.com
    env:
      NUXT_PAGE: flytirol
      SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
      SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install
      - name: create-public
        run: yarn create-public
      - name: get image-optimizer
        run: curl -L https://github.com/naschidaniel/image-optimizer/releases/download/v0.3.6/image-optimizer-linux --output image-optimizer && chmod +x image-optimizer
      - name: optimize-images
        run: yarn optimize-images
      - name: generateContent
        run: yarn generateContent
      - name: build
        run: yarn build
      - name: Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fly-tirol_build
          path: dist
          retention-days: 0.1
