on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

name: Build white-cloud.tirol

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build white-cloud.tirol
    env:
      NUXT_PAGE: flytirol
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: yarn install
      - name: create .nuxt tsconfig
        run: mkdir .nuxt && echo "{}" > .nuxt/tsconfig.json
      - name: create-public
        run: yarn create-public
      - name: get image-optimizer
        run: curl -L https://github.com/naschidaniel/image-optimizer/releases/download/v0.5.0/image-optimizer-linux --output image-optimizer && chmod +x image-optimizer
      - name: optimize-images
        run: yarn optimize-images
      - name: generateContent
        run: yarn generateContent
      - name: build
        run: yarn build
      - name: Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: whitecloud_build
          path: .output
          retention-days: 0.1
