on: workflow_dispatch

name: deploy manually to server

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    name: deploy fly-tirol.com
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - uses: actions/download-artifact@v2
        with:
          name: fly-tirol_build
          path: ./dist
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/www/flytirol/site/
